name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.13.1
  widgetbook_annotation: ^3.4.0
  google_fonts: ^6.2.1
  capstone_frontend:
    path: ../
  flutter_otp_text_field: ^1.5.1+1
  flutter_bloc: ^8.1.3
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.12.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
